# ----------------------------------------------------
# Module 2: Statistical Analysis in R
# ----------------------------------------------------

# --- 1. Load Libraries ---
# Load our installed packages
library(dplyr)
library(ggplot2)

print("Libraries loaded.")

# --- 2. Import Data (Unit III) ---
# Read the CSV file generated by our Python script
# This loads it into a "Data Frame"
# If RStudio imported it as "classroom_log", just rename it to "data"
data <- classroom_log
print("Data successfully imported.")

# --- 3. Initial Data Inspection (Unit III) ---
# 'glimpse' is a powerful way to see all our columns and data types
print("--- Data Glimpse ---")
glimpse(data)

# 'summary' gives us a quick statistical overview (Unit II)
print("--- Data Summary ---")
summary(data)

# --- 4. Data Cleaning & Preparation (Unit III) ---
# The 'status' column is text, but R should treat it as a category.
# We convert it to a "Factor"
data$status <- as.factor(data$status)

# The 'timestamp' is text. Let's convert it to a real datetime object
data$timestamp <- as.POSIXct(data$timestamp, format = "%Y-%m-%dT%H:%M:%OS")

print("--- Cleaned Data ---")
glimpse(data)
# --- 5. Descriptive Statistics (Unit II) ---
# Calculate overall class average attention
class_avg_score <- mean(data$attentiveness_score)
print(paste("Overall Class Average Attentiveness:", class_avg_score))

# Calculate average attention PER STUDENT
student_summary <- data %>%
  group_by(roll_no) %>%
  summarise(
    avg_score = mean(attentiveness_score),
    median_score = median(attentiveness_score),
    std_dev = sd(attentiveness_score),
    time_points = n()
  )

print("--- Summary by Student ---")
print(student_summary)

# --- 6. Visualizations (Unit V) ---

# Plot 1: Box Plot (Quartile Analysis)
# This lets us compare all students against each other.
plot1_boxplot <- ggplot(data, aes(x = roll_no, y = attentiveness_score, fill = roll_no)) +
  geom_boxplot() +
  labs(
    title = "Student Attentiveness Distribution (Unit V)",
    subtitle = "Comparing score distributions for each student",
    x = "Student Roll Number",
    y = "Attentiveness Score"
  ) +
  theme_minimal() +
  theme(legend.position = "none") # Hide legend, as X-axis is clear

print(plot1_boxplot)


# Plot 2: Line Graph (Class Attentiveness Over Time)
# This shows us the engagement pattern for the whole class.
# We will "bin" the time into 10-second intervals for a smoother graph.
plot2_linegraph <- data %>%
  mutate(time_bin = cut(timestamp, breaks = "10 sec")) %>%
  group_by(time_bin) %>%
  summarise(class_avg_score = mean(attentiveness_score)) %>%
  # We need to convert the time_bin back to a datetime to plot it
  mutate(time_bin = as.POSIXct(time_bin)) %>%
  
  ggplot(aes(x = time_bin, y = class_avg_score)) +
  geom_line(color = "blue", size = 1) +
  geom_point(color = "blue") +
  labs(
    title = "Average Class Attentiveness Over Time (Unit V)",
    subtitle = "Scores aggregated into 10-second intervals",
    x = "Time",
    y = "Average Attentiveness Score"
  ) +
  theme_minimal()

print(plot2_linegraph)